# Generated by Django 3.1.5 on 2025-03-26 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0002_auto_20241020_1126'),
        ('central_mess', '0002_auto_20241012_1459'),
    ]

    operations = [
    ]
