# Generated by Django 3.1.5 on 2025-03-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcomplain',
            name='upload_resolved',
            field=models.FileField(blank=True, null=True, upload_to='resolved_complaints/'),
        ),
    ]
